/**
 * Student Name: Thomas Herr
 * Student Number: 200325519
 * Purpose: Allow users to view package configurations for local auto center
 */
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AutoCenter
{
    public partial class AutoCenterForm : Form
    {
        /**
         * Factory class generates package arrays for us based on specified input
         */
        PackageFactory pkgFactory = new PackageFactory();

        /**
         * Constructor
         */
        public AutoCenterForm()
        {
            InitializeComponent();
        }

        /**
         * Event handler for packageComboBox item changed event, fires when a new value is selected
         */
        private void packageComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            //Empty the output
            packageTextBox.Text = String.Empty;
            ComboBox comboBox = (ComboBox)sender;

            //If nothing was selected exit out immediatly before wasting any time
            if (packageComboBox.SelectedItem == null)
            {
                return;
            }

            //Set the array that will store our display data, this is generated by the package factory class
            string[][] data = this.pkgFactory.getPackage(comboBox.SelectedItem.ToString(), null);

            displayOutput(data, 0, packageTextBox);

            //Simulate a click on the fragrance box to make it update the UI
            if (fragranceComboBox.SelectedItem!=null)
            {
                fragranceComboBox_SelectedIndexChanged(fragranceComboBox, e);
            }
        }

        /**
         * Event handler for fragranceComboBox item changed event, fires when a new value is selected
         */
        private void fragranceComboBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            //Empty the output
            fragranceTextBox.Text = String.Empty;
            ComboBox comboBox = (ComboBox)sender;

            //If nothing was selected exit out immediatly before wasting any time
            if (fragranceComboBox.SelectedItem == null)
            {
                return;
            }

            //Set the array that will store our display data, this is generated by the package factory class
            string[][] data = this.pkgFactory.getPackage(packageComboBox.SelectedItem.ToString(), comboBox.SelectedItem.ToString());

            //Consume the arrays provided

            displayOutput(data, 1, fragranceTextBox);
        }
        /**
         * Format data and display to given output textbox
         */
        private void displayOutput(string[][] data, int depth, TextBox output)
        {
            //Consume the arrays provided
            for (int x = 0; x < data[depth].Length; x++)
            {
                //First item to be displayed, output a comma after it for formatting
                if (x == 0 && x != data[depth].Length - 1)
                {
                    output.Text += data[depth][x] + ",";
                    //Last item to be displayed, dont place a comma at the end
                }
                else if (x == data[depth].Length - 1)
                {
                    output.Text += " " + data[0][x];
                }
                //Middle item, make sure it has a comma for formatting
                else
                {
                    output.Text += " " + data[depth][x] + ",";
                }
            }
        }
        /**
         * Context menu about click event handler
         */
        private void aboutToolStripMenuItem_Click(object sender, EventArgs e)
        {
            //Show the about form when requested
            AboutForm aboutForm = new AboutForm();
            aboutForm.Show();
        }
        /**
         * Context menu clear click event handler
         */
        private void clearToolStripMenuItem_Click(object sender, EventArgs e)
        {
            //Setting both of these to null will trigger the selected change event handled above so outputs will be automatically updated
            fragranceComboBox.SelectedItem = null;
            packageComboBox.SelectedItem = null;
        }
        /**
         * Context Menu exit click event handler
         */
        private void exitToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }
    }
}
